#!/usr/bin/env python
import sys
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('--refs', '-r', default='data/dev.refs')
args = parser.parse_args()

score = 0.0
sentence_count = 0
for hyps, ref in zip(sys.stdin, open(args.refs)):
	hyps = [hyp.strip() for hyp in hyps.strip().split('|||')]
	ref = ref.strip()

	for i, hyp in enumerate(hyps):
		if hyp == ref:
			score += 1.0 / (i + 1)
			break
	sentence_count += 1

# prevent pipe error
for _ in sys.stdin:
	pass

print 'MRR: %f' % (score / sentence_count)
